name: Release MacOS.

on: [push]

jobs:

  check:
    if: "!(contains(github.event.head_commit.message, '[skip ci]'))"
    name: Parse parameters
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.parse.outputs.build }}
      ref: ${{ steps.parse.outputs.ref }}
      update: ${{ steps.parse.outputs.update }}
      packer: ${{ steps.parse.outputs.packer }}
      telegram: ${{ steps.parse.outputs.telegram }}
      description: ${{ steps.parse.outputs.description }}
      cache: ${{ steps.parse.outputs.cache }}

    steps:
      - name: Clone scripts.
        uses: actions/checkout@v2
      - name: Parse commit description
        id: parse
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          script: |
            const path = require('path');
            const currentBuild = "mac";
            const scriptPath = path.resolve('./scripts/option_parser.js');
            require(scriptPath)({github, context, currentBuild});

  build:
    name: Build on latest macOS
    needs: check
    if: needs.check.outputs.build == 'true'
    runs-on: macos-latest

    env:
      GIT: "https://github.com"
      PKG_CONFIG_PATH: /usr/local/ffmpeg/lib/pkgconfig
      CMAKE_LIBRARY_PATH: /usr/local/ffmpeg/lib
      OPENALDIR: /usr/local/opt/openal-soft
      OPENSSL_ROOT_DIR: /usr/local/opt/openssl@1.1
      Qt5_DIR: /usr/local/opt/qt@5/lib/cmake/Qt5
      ONLY_CACHE: "false"
      MANUAL_CACHING: "1"
      REPO_NAME: "kotatogram/kotatogram-desktop"
      AUTO_CACHING: "1"

    steps:
      - name: Clone.
        uses: actions/checkout@v2
        with:
          repository: ${{ env.REPO_NAME }}
          submodules: recursive
          path: ${{ env.REPO_NAME }}
          ref: ${{ needs.check.outputs.ref }}

      - name: Clone scripts.
        uses: actions/checkout@v2
        with:
          path: buildscripts

      - name: Parse current version.
        shell: bash
        run: ./buildscripts/scripts/parse_version.sh

      - name: First set up.
        run: |
          brew install autoconf automake cmake meson openal-soft openssl opus nasm ninja pkg-config python qt@5 yasm xz
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

          xcodebuild -version > CACHE_KEY.txt
          echo $MANUAL_CACHING >> CACHE_KEY.txt
          echo "$GITHUB_WORKSPACE" >> CACHE_KEY.txt
          if [ "$AUTO_CACHING" == "1" ]; then
            thisFile=buildscripts/.github/workflows/mac-release.yml
            echo `md5 -q $thisFile` >> CACHE_KEY.txt
          fi
          echo "CACHE_KEY=`md5 -q CACHE_KEY.txt`" >> $GITHUB_ENV

          echo /usr/local/opt/qt@5/bin >> $GITHUB_PATH

          mkdir -p Libraries/macos
          cd Libraries/macos
          echo "LibrariesPath=`pwd`" >> $GITHUB_ENV

          curl -o tg_owt-version.json https://api.github.com/repos/desktop-app/tg_owt/git/refs/heads/master

      - name: Setting up updater keys.
        if: >
          needs.check.outputs.update == 'true'
          && needs.check.outputs.packer == 'true'
        env:
          PACKER_PRIVATE_KEY: ${{ secrets.PACKER_PRIVATE_KEY }}
          PACKER_PRIVATE_BETA_KEY: ${{ secrets.PACKER_PRIVATE_BETA_KEY }}
        run: python3 buildscripts/scripts/updater_keys.py

      - name: Rnnoise.
        run: |
          cd $LibrariesPath

          git clone --depth=1 https://gitlab.xiph.org/xiph/rnnoise.git
          cd rnnoise
          ./autogen.sh
          ./configure --disable-examples --disable-doc
          make -j$(sysctl -n hw.logicalcpu)
          make install

      - name: FFmpeg cache.
        id: cache-ffmpeg
        uses: actions/cache@v2
        with:
          path: ${{ env.LibrariesPath }}/ffmpeg-cache
          key: ${{ runner.OS }}-ffmpeg-${{ env.CACHE_KEY }}
      - name: FFmpeg build.
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        run: |
          cd $LibrariesPath

          git clone --branch release/4.4 $GIT/FFmpeg/FFmpeg ffmpeg
          cd ffmpeg
          ./configure \
          --prefix=/usr/local/ffmpeg \
          --disable-debug \
          --disable-programs \
          --disable-doc \
          --disable-network \
          --disable-autodetect \
          --disable-encoders \
          --disable-muxers \
          --disable-bsfs \
          --disable-protocols \
          --disable-devices \
          --disable-filters \
          --disable-iconv \
          --enable-audiotoolbox \
          --enable-videotoolbox \
          --enable-libopus \
          --enable-protocol=file \
          --enable-encoder=libopus \
          --enable-muxer=ogg \
          --enable-muxer=opus

          make -j$(sysctl -n hw.logicalcpu)
          sudo make DESTDIR="$LibrariesPath/ffmpeg-cache" install
          cd ..
          rm -rf ffmpeg
      - name: FFmpeg install.
        run: |
          cd $LibrariesPath
          sudo cp -R ffmpeg-cache/. /

      - name: WebRTC cache.
        id: cache-webrtc
        uses: actions/cache@v2
        with:
          path: ${{ env.LibrariesPath }}/tg_owt
          key: ${{ runner.OS }}-webrtc-${{ env.CACHE_KEY }}-${{ hashFiles('**/tg_owt-version.json') }}
      - name: WebRTC.
        if: steps.cache-webrtc.outputs.cache-hit != 'true'
        run: |
          cd $LibrariesPath

          git clone --recursive --depth=1 $GIT/desktop-app/tg_owt.git
          cd tg_owt

          cmake -B build . \
          -GNinja \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_SHARED_LIBS=OFF \
          -DTG_OWT_BUILD_AUDIO_BACKENDS=OFF \
          -DTG_OWT_PACKAGED_BUILD_FFMPEG_STATIC=ON

          cmake --build build -j$(sysctl -n hw.logicalcpu)

      - name: Kotatogram Desktop build.
        if: env.ONLY_CACHE == 'false'
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          tg_owt_DIR: ${{ env.LibrariesPath }}/tg_owt/build
        run: |
          cd $REPO_NAME

          UPDDEFINE="OFF"
          ${{ needs.check.outputs.update }} || UPDDEFINE="ON"

          PACKERDEFINE="ON"
          ${{ needs.check.outputs.packer }} || PACKERDEFINE="OFF"

          cmake -Bbuild -GNinja . \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_FIND_FRAMEWORK=LAST \
          -DCMAKE_EXE_LINKER_FLAGS="-s" \
          -DTDESKTOP_API_ID=${API_ID} \
          -DTDESKTOP_API_HASH=${API_HASH} \
          -DDESKTOP_APP_DISABLE_AUTOUPDATE=${UPDDEFINE} \
          -DKTGDESKTOP_ENABLE_PACKER=${PACKERDEFINE} \
          -DDESKTOP_APP_USE_PACKAGED_LAZY=ON \
          -DDESKTOP_APP_USE_PACKAGED_FFMPEG_STATIC=ON

          cmake --build build -j$(sysctl -n hw.logicalcpu)

          cd build
          macdeployqt Kotatogram.app
          codesign --remove-signature Kotatogram.app

          tag_name=${{ needs.check.outputs.display_version }}
          artifact_name=${{ env.VERSION_STR }}-macos.dmg
          echo "ARTIFACT_NAME=$artifact_name" >> $GITHUB_ENV

          mkdir dmgsrc
          mv Kotatogram.app dmgsrc
          hdiutil create -volname Kotatogram -srcfolder dmgsrc -ov -format UDZO $artifact_name

      - name: Upload artifact.
        if: env.ONLY_CACHE == 'false'
        uses: actions/upload-artifact@v2
        with:
          path: ./${{ env.REPO_NAME }}/build/${{ env.ARTIFACT_NAME }}
          name: Binary

      - name: Install dependencies for Telegram uploader.
        if: >
          env.ONLY_CACHE == 'false'
          && needs.check.outputs.telegram == 'true'
        run: |
          python3 -m pip install telethon cryptg

      - name: Upload binary to Telegram.
        if: >
          env.ONLY_CACHE == 'false'
          && needs.check.outputs.telegram == 'true'
        env:
          TELETHON_API_ID: ${{ secrets.TELETHON_API_ID }}
          TELETHON_API_HASH: ${{ secrets.TELETHON_API_HASH }}
          TELETHON_SESSION: ${{ secrets.TELETHON_SESSION }}
        run: >
          python3 buildscripts/scripts/uploader.py
          "@ktgbuilds"
          "${{ env.REPO_NAME }}/build/${{ env.ARTIFACT_NAME }}"
          "#macOS"

      - name: Package update.
        if: >
          env.ONLY_CACHE == 'false'
          && needs.check.outputs.update == 'true'
          && needs.check.outputs.packer == 'true'
        run: |
          cd $REPO_NAME

          ./build/Packer -version ${{ env.VERSION_NUM }}${{ env.PACKER_BETA }} \
          -path build/dmgsrc/Kotatogram.app \
          -target mac

          tar -caf tmacupd${{ env.VERSION_NUM }}.tar.xz tmacupd${{ env.VERSION_NUM }}
          echo ""UPDATE_FILE=tmacupd${{ env.VERSION_NUM }}"" >> $GITHUB_ENV

      - name: Upload update artifact.
        uses: actions/upload-artifact@v2
        if: >
          env.ONLY_CACHE == 'false'
          && needs.check.outputs.update == 'true'
          && needs.check.outputs.packer == 'true'
        with:
          path: ./${{ env.REPO_NAME }}/${{ env.UPDATE_FILE }}
          name: Update file

      - name: Upload update to Telegram.
        if: >
          env.ONLY_CACHE == 'false'
          && needs.check.outputs.update == 'true'
          && needs.check.outputs.packer == 'true'
          && needs.check.outputs.telegram == 'true'
        env:
          TELETHON_API_ID: ${{ secrets.TELETHON_API_ID }}
          TELETHON_API_HASH: ${{ secrets.TELETHON_API_HASH }}
          TELETHON_SESSION: ${{ secrets.TELETHON_SESSION }}
        run: >
          python3 buildscripts/scripts/uploader.py
          "@ktghbcfiles"
          "${{ env.REPO_NAME }}/${{ env.UPDATE_FILE }}"
          "${{ needs.check.outputs.description }}"
